; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
lib_ldf_mode = deep
monitor_speed = 115200
monitor_filters = time, log2file
board_build.partitions = partitions/partition_ota.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    -DCONFIG_BT_NIMBLE_ACL_BUF_COUNT=20
    -DCONFIG_BT_NIMBLE_ACL_BUF_SIZE=251
lib_deps = 
	adafruit/Adafruit MPU6050@^2.2.9
	tanakamasayuki/TensorFlowLite_ESP32
	adafruit/Adafruit INA219@^1.2.3
	heltecautomation/Heltec ESP32 Dev-Boards@^1.1.2
